services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
      - GO_JUDGE_ENDPOINT=http://go-judge:5050
    restart: unless-stopped
    depends_on:
      - go-judge

  go-judge:
    image: criyle/go-judge:latest
    ports:
      - "5050:5050"
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
