services:
  app:
    image: bots-nest:latest
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
      - GO_JUDGE_ENDPOINT=http://go-judge:5050
    restart: unless-stopped
    depends_on:
      - go-judge

  go-judge:
    image: bots-nest-judge:latest
    ports:
      - "5050:5050"
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped

  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8079:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped

volumes:
  weaviate_data:
